#!/bin/bash

# Tutorials:
for i in {1..7}; do
    images=$(grep -oE '!\[\]\(\.\./images/[^)]+\)' week${i}/tutorial/tutorial-0${i}.qmd | sed -E 's/!\[\]\(\.\.\/images\/([^)]+)\)/\1/')
    mkdir -p week${i}/images
    for image in $images; do
        echo "Processing image: $image"
        # Use the cp command to copy the file to the new location
        cp "images/"$image week${i}/images/
    done
done

echo "Processing lecture images"

# Lectures:
for i in {1..7}; do
    echo "Lecture ${i}"
    images=$(grep -oE '!\[\]\(images/[^)]+\)' week${i}/index.qmd | sed -E 's/!\[\]\(images\/([^)]+)\)/\1/')
    mkdir -p week${i}/images
    for image in $images; do
        echo "Processing image: $image"
        # Use the cp command to copy the file to the new location
        cp "images/"$image week${i}/images/
    done
done