---
title: 'ETC5513: Collaborative and Reproducible Practices'
subtitle: "Tutorial 8"
author: "Michael Lydeamore"
date: today
format:
    unilur-html:
        output-file: index.html
        embed-resources: true
    unilur-html+solution:
        output-file: solution.html
        embed-resources: true
---
```{r, echo = FALSE, eval = file.exists("tutorial.css")}
htmltools::includeCSS("tutorial.css")
```


## `r emo::ji("target")` Objectives

* Create a reproducible PDF report using a template
* Work in groups to create a joint report using version control
* Practice all markdown tools that we have learnt

##  Create a reproducible and collaborative report

Form a group of 3 or 4 people, with whom you will create a reproducible and collaborative report.

In this group:

* Nominate a person who will create a GitHub repo with a `README.md` file. The repo can be public or private.

* Clone the repository locally, and set up a template, either one from the [Monash templates](https://robjhyndman.com/hyndsight/quarto_templates.html) or the [Quarto Journals system](https://quarto.org/docs/journals/)

::: {.unilur-solution}
Since the repository has already been created, we have to use the command to add it to a pre-existing repository:

`quarto add numbats/monash-quarto-letter`

or

`quarto install extension numbats/monash-quarto-letter`

Note if you don't have quarto on your path, this command may not work. If so, install the Quarto binary.
:::

* Create a new Quarto document, and change the output format to match the template you have picked.

::: {.unilur-solution}
For us, that is:

```
format: memo-pdf
```
:::

* Add a chunk that loads in the data you can find under this week's Moodle.

::: {.unilur-solution}
```
covid_data <- read_csv(file = "Data/worldwidecases.csv")
```
:::

* Stage, commit and push these changes to the remote (GitHub).

* Invite your teammates to collaborate as you have done in the previous tutorials.

## Working together

**Each team member**:

* Make their own branch
* Work in their _own_ section - give everyone a number, and they only work in that section
* In each section, create a figure and describe what you observe from the figure.

Make sure the figure has a caption, and a label, and that the figure is cross-referenced in the text.

* Stage, commit and push changes as you progress - don't leave it all until the end.

## Creating a single report

Once each team member has finished working on their section, please merge the changes into the main branch. The final document should be in the main branch and include each section from each team member. All cross-references should be shown and function as expected.